name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test_django:
    uses: https://github.com/olara87/django-k8s-cluster-new/.github/workflows/test_django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
    steps:
    - uses: actions/checkout@v3